[package]
name = "marketwise-news"
version = "0.1.0"
edition = "2021"

[dependencies]
json = "0.12.4"
metaculustetra = "0.0.5"
reqwest = { version = "0.11.22" , features = ["blocking"] }
sqlite = "0.32.0"
